//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderActivities
    {
        public int WorkOrderCode { get; set; }
        public int ActivityCode { get; set; }
        public string ActivityDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool WorkOrderStatus { get; set; }
    }
}
